services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./:/var/www/html
      - ./environment/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    expose:
      - "80"
  php-fpm:
    restart: unless-stopped
    build:
      dockerfile: environment/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./environment/php-fpm/php.ini-production:/usr/local/etc/php/php.ini
  worker:
    build:
      dockerfile: environment/php-fpm/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - php-fpm
  worker_database:
    extends:
      service: worker
    command: "/var/www/html/bin/console messenger:consume game_reward scheduler_game_map_spawn"
  worker_game_activity:
    extends:
      service: worker
    command: "/var/www/html/bin/console messenger:consume game_activity --sleep=0.05"
